// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmimYwKo5W40_eDcUO9Q4kz6OLygBgpqA',
    appId: '1:892366858823:web:b497ad3bb249fea2e49f62',
    messagingSenderId: '892366858823',
    projectId: 'platform-project-76360',
    authDomain: 'platform-project-76360.firebaseapp.com',
    databaseURL: 'https://platform-project-76360-default-rtdb.firebaseio.com',
    storageBucket: 'platform-project-76360.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF1ezOeY9BuwiftN9RYeYX0E6tXf3R7qE',
    appId: '1:892366858823:android:baf6da68b974e5a9e49f62',
    messagingSenderId: '892366858823',
    projectId: 'platform-project-76360',
    databaseURL: 'https://platform-project-76360-default-rtdb.firebaseio.com',
    storageBucket: 'platform-project-76360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjlySD1s1nTjFvad5Le6PrKwoe0LBjdk',
    appId: '1:892366858823:ios:4cc4684c951b83e1e49f62',
    messagingSenderId: '892366858823',
    projectId: 'platform-project-76360',
    databaseURL: 'https://platform-project-76360-default-rtdb.firebaseio.com',
    storageBucket: 'platform-project-76360.appspot.com',
    iosClientId: '892366858823-0bmtmdq5ih5f8m4qrlrtt0f4hebkpv9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.testConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGjlySD1s1nTjFvad5Le6PrKwoe0LBjdk',
    appId: '1:892366858823:ios:4cc4684c951b83e1e49f62',
    messagingSenderId: '892366858823',
    projectId: 'platform-project-76360',
    databaseURL: 'https://platform-project-76360-default-rtdb.firebaseio.com',
    storageBucket: 'platform-project-76360.appspot.com',
    iosClientId: '892366858823-0bmtmdq5ih5f8m4qrlrtt0f4hebkpv9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.testConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmimYwKo5W40_eDcUO9Q4kz6OLygBgpqA',
    appId: '1:892366858823:web:658a9f727cb47589e49f62',
    messagingSenderId: '892366858823',
    projectId: 'platform-project-76360',
    authDomain: 'platform-project-76360.firebaseapp.com',
    databaseURL: 'https://platform-project-76360-default-rtdb.firebaseio.com',
    storageBucket: 'platform-project-76360.appspot.com',
  );
}
